### ISSUE TITLE
FTBFS after commit 94e2eb2 - shebang line was removed

### ISSUE THREAD

**Issue by vrutkovs** [pwithnall/uhttpmock#1]
In commit 94e2eb24 shebang was removed and it broke Continuous build

See [log](http://build.gnome.org/continuous/buildmaster/builds/2015/02/07/21/build/log-uhttpmock.txt)

**Comment by pwithnall** [comment]
Whoops. Thanks for the bug report. Fixed in commit 9fe06a7cce553459af481df8a24e4ca4bb76155b.
