### ISSUE TITLE
deprecated functions 

### ISSUE THREAD

**Issue by JulioOrdonezV** [pwithnall/uhttpmock#2]
libuhttpmock/uhm-resolver.c: In function 'uhm_resolver_lookup_by_name_async':
libuhttpmock/uhm-resolver.c:180:2: error: 'g_simple_async_result_new' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:51): Use 'g_task_new' instead [-Werror=deprecated-declarations]
  res = g_simple_async_result_new (G_OBJECT (resolver), callback, user_data, NULL);
  ^
libuhttpmock/uhm-resolver.c:183:3: error: 'g_simple_async_result_set_op_res_gpointer' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:75) [-Werror=deprecated-declarations]
   g_simple_async_result_set_op_res_gpointer (res, addr, NULL);
   ^
libuhttpmock/uhm-resolver.c:185:3: error: 'g_simple_async_result_set_from_error' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:113) [-Werror=deprecated-declarations]
   g_simple_async_result_set_from_error (res, error);
   ^
libuhttpmock/uhm-resolver.c:189:2: error: 'g_simple_async_result_complete_in_idle' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:106) [-Werror=deprecated-declarations]
  g_simple_async_result_complete_in_idle (res);
  ^
libuhttpmock/uhm-resolver.c: In function 'uhm_resolver_lookup_by_name_finish':
libuhttpmock/uhm-resolver.c:198:2: error: 'g_simple_async_result_propagate_erro' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:119) [-Werror=deprecated-declarations]
  if (g_simple_async_result_propagate_error (simple, error)) {
  ^
libuhttpmock/uhm-resolver.c:202:2: error: 'g_simple_async_result_get_op_res_gpointer' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:79) [-Werror=deprecated-declarations]
  return g_simple_async_result_get_op_res_gpointer (simple);
  ^
libuhttpmock/uhm-resolver.c: In function 'uhm_resolver_lookup_service_async':
libuhttpmock/uhm-resolver.c:227:2: error: 'g_simple_async_result_new' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:51): Use 'g_task_new' instead [-Werror=deprecated-declarations]
  res = g_simple_async_result_new (G_OBJECT (resolver), callback, user_data, uhm_resolver_lookup_service_async);
  ^
libuhttpmock/uhm-resolver.c:230:3: error: 'g_simple_async_result_set_op_res_gpointer' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:75) [-Werror=deprecated-declarations]
   g_simple_async_result_set_op_res_gpointer (res, addr, NULL);
   ^
libuhttpmock/uhm-resolver.c:232:3: error: 'g_simple_async_result_set_error' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:122) [-Werror=deprecated-declarations]
   g_simple_async_result_set_error (res, G_RESOLVER_ERROR, G_RESOLVER_ERROR_NOT_FOUND, "No fake SRV record registered for ‘%s’.", rrname);
   ^
libuhttpmock/uhm-resolver.c:235:2: error: 'g_simple_async_result_complete_in_idle' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:106) [-Werror=deprecated-declarations]
  g_simple_async_result_complete_in_idle (res);
  ^
libuhttpmock/uhm-resolver.c: In function 'uhm_resolver_lookup_service_finish':
libuhttpmock/uhm-resolver.c:244:2: error: 'g_simple_async_result_propagate_erro' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:119) [-Werror=deprecated-declarations]
  if (g_simple_async_result_propagate_error (simple, error)) {
  ^
libuhttpmock/uhm-resolver.c:248:2: error: 'g_simple_async_result_get_op_res_gpointer' is deprecated (declared at /home/julio/jhbuild/install/include/glib-2.0/gio/gsimpleasyncresult.h:79) [-Werror=deprecated-declarations]
  return g_simple_async_result_get_op_res_gpointer (simple);
  ^
cc1: all warnings being treated as errors

compiling in fedora 21

**Comment by pwithnall** [comment]
Fixed in commit 3c5d031.
